### ISSUE TITLE
EROOR

### ISSUE THREAD

**Issue by chathurip** [anaskhan96/Movie-Recommendation#1]
When running app.py i get this type of eroor

AttributeError: module 'sys' has no attribute 'setdefaultencoding'

How i fix this?????

**Comment by anaskhan96** [comment]
You are most likely using Python 3.x and `sys.setdefaultencoding()` is only available in Python 2.x

**Comment by chathurip** [comment]
then i commented #sys.setdefaultencoding("utf-8") and run then it gives 
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat 

can i get simple explanation of the system,how codes work,after compiled app.py what is the next step?

**Comment by chathurip** [comment]
I mailed you,about my problem,could you please check it??

**Comment by anaskhan96** [comment]
The above message indicates that a server is running on port 5000, with debugging enabled. However, if that didn't make any sense to you, I think you need to brush up on your Python and the basics of how web servers work, followed by going through the [documentation of Flask](http://flask.pocoo.org/docs/0.12/), which is the web framework used in this repository.
